services:
  local-db:
    profiles:
      - localmysql

  web:
    env_file:
      - .env.cloudsql
    depends_on: !override
      cloud-sql-proxy:
        condition: service_started

  cloud-sql-proxy:
    profiles: !override []
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/gcp-key.json
    volumes: !override
      - ./gcp-key.json:/secrets/gcp-key.json:ro
