import{ChangeDetectionStrategy,Component,OnInit,inject,signal}from'@angular/core';
import{FormsModule}from'@angular/forms';import{ActivatedRoute,RouterLink}from'@angular/router';
import{CounsellingSummary,OutcomeData,OutcomePayload,OutcomePolicy}from'../core/api.models';
import{SmartCounsellingApiError,SmartCounsellingApiService}from'../core/smart-counselling-api.service';
import{CounsellingStepperComponent}from'../shared/counselling-stepper.component';import{PageHeaderComponent}from'../shared/page-header.component';
@Component({selector:'sc-outcome',imports:[FormsModule,RouterLink,CounsellingStepperComponent,PageHeaderComponent],templateUrl:'./outcome.component.html',changeDetection:ChangeDetectionStrategy.OnPush})
export class OutcomeComponent implements OnInit{private api=inject(SmartCounsellingApiService);private route=inject(ActivatedRoute);readonly sessionId=Number(this.route.snapshot.paramMap.get('sessionId'));readonly data=signal<OutcomeData|null>(null);readonly completed=signal<CounsellingSummary|null>(null);readonly loading=signal(true);readonly saving=signal(false);readonly error=signal('');form:OutcomePayload={outcome:'',outcomeReason:null,nextAction:'',nextFollowupDate:null,staffNotes:null};review=false;
ngOnInit(){this.api.getOutcome(this.sessionId).subscribe({next:x=>{this.data.set(x);this.form={outcome:x.current.outcome||'',outcomeReason:x.current.outcomeReason,nextAction:x.current.nextAction||'',nextFollowupDate:x.current.nextFollowupDate,staffNotes:x.current.staffNotes};if(x.summary.status==='COMPLETED')this.completed.set(x.summary);this.loading.set(false);},error:e=>this.fail(e)});}
policy():OutcomePolicy|null{return this.data()?.policies.find(x=>x.code===this.form.outcome)||null;}selectOutcome(code:string){this.form.outcome=code;this.form.outcomeReason=null;this.form.nextAction='';if(!this.policy()?.requiresFollowup)this.form.nextFollowupDate=null;this.review=false;}quick(days:number){const d=new Date();d.setDate(d.getDate()+days);this.form.nextFollowupDate=d.toISOString().slice(0,10);}saveDraft(){this.saving.set(true);this.error.set('');this.api.saveOutcome(this.sessionId,this.form).subscribe({next:x=>{this.data.set(x);this.saving.set(false);this.review=true;},error:e=>{this.saving.set(false);this.fail(e);}});}complete(){this.saving.set(true);this.error.set('');this.api.completeCounselling(this.sessionId,this.form).subscribe({next:x=>{this.completed.set(x);this.saving.set(false);window.scrollTo({top:0,behavior:'smooth'});},error:e=>{this.saving.set(false);this.fail(e);}});}handoff(){this.api.openAdmissionHandoff(this.sessionId).subscribe({next:x=>{if(x.available&&x.url)window.location.assign(x.url);else if(x.student)this.completed.update(s=>s?{...s,admissionHandoffAvailable:false,student:x.student||null}:s);},error:e=>this.fail(e)});}label(x:string|null){return(x||'—').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());}private fail(e:unknown){this.loading.set(false);this.error.set(e instanceof SmartCounsellingApiError?e.message:'The counselling outcome could not be saved.');}}
